services:
  - type: web
    name: pocketbase
    env: docker
    plan: free
    autoDeploy: false
    buildCommand: ""
    startCommand: ./start.sh
    envVars:
      - key: PORT
        value: 10000
